server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://116.205.181.81:3306/pi?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver